CREATE TABLE IF NOT EXISTS schema_migrations (
  version VARCHAR(64) NOT NULL PRIMARY KEY,
  applied_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE TABLE IF NOT EXISTS kb_nodes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(16) NOT NULL,
  parent_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  name VARCHAR(80) NOT NULL,
  icon_url MEDIUMTEXT NULL,
  sort INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  INDEX idx_kb_nodes_parent (parent_id, sort, id),
  INDEX idx_kb_nodes_deleted (deleted_at)
);

CREATE TABLE IF NOT EXISTS kb_docs (
  node_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  content_md LONGTEXT NOT NULL,
  current_version INT NOT NULL DEFAULT 0,
  views BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  CONSTRAINT fk_kb_docs_node FOREIGN KEY (node_id) REFERENCES kb_nodes(id),
  INDEX idx_kb_docs_deleted (deleted_at)
);

