CREATE TABLE IF NOT EXISTS k8s_permission_audits (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_type VARCHAR(32) NOT NULL,
  cluster_id BIGINT UNSIGNED NULL,
  cluster_name VARCHAR(128) NOT NULL DEFAULT '',
  display_name VARCHAR(160) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL,
  mode VARCHAR(32) NOT NULL DEFAULT 'full',
  task_id BIGINT UNSIGNED NULL,
  request_json JSON NULL,
  summary_json JSON NULL,
  stats_json JSON NULL,
  error_json JSON NULL,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  KEY idx_k8s_permission_audits_source_type (source_type),
  KEY idx_k8s_permission_audits_cluster_id (cluster_id),
  KEY idx_k8s_permission_audits_status (status),
  KEY idx_k8s_permission_audits_task_id (task_id),
  KEY idx_k8s_permission_audits_created_by (created_by),
  KEY idx_k8s_permission_audits_created_at (created_at),
  KEY idx_k8s_permission_audits_deleted_at (deleted_at)
);

CREATE TABLE IF NOT EXISTS k8s_permission_audit_findings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  audit_id BIGINT UNSIGNED NOT NULL,
  finding_type VARCHAR(32) NOT NULL,
  risk_level VARCHAR(16) NOT NULL DEFAULT 'low',
  ownership_class VARCHAR(16) NOT NULL DEFAULT 'unrelated',
  privilege_class VARCHAR(32) NOT NULL DEFAULT '',
  scope VARCHAR(16) NOT NULL DEFAULT '',
  deployment_blocker TINYINT(1) NOT NULL DEFAULT 0,
  depends_on_shared_cluster_capability TINYINT(1) NOT NULL DEFAULT 0,
  api_version VARCHAR(64) NOT NULL DEFAULT '',
  kind VARCHAR(64) NOT NULL DEFAULT '',
  namespace VARCHAR(128) NOT NULL DEFAULT '',
  name VARCHAR(160) NOT NULL DEFAULT '',
  workload_kind VARCHAR(64) NOT NULL DEFAULT '',
  workload_name VARCHAR(160) NOT NULL DEFAULT '',
  service_account_name VARCHAR(160) NOT NULL DEFAULT '',
  summary VARCHAR(512) NOT NULL DEFAULT '',
  reason_codes_json JSON NULL,
  detail_json JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_k8s_permission_audit_findings_audit_id (audit_id),
  KEY idx_k8s_permission_audit_findings_type (finding_type),
  KEY idx_k8s_permission_audit_findings_risk_level (risk_level),
  KEY idx_k8s_permission_audit_findings_ownership (ownership_class),
  KEY idx_k8s_permission_audit_findings_namespace (namespace),
  KEY idx_k8s_permission_audit_findings_kind (kind)
);
