CREATE TABLE IF NOT EXISTS manifest_apply_records (
  id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cluster_id        BIGINT UNSIGNED NOT NULL DEFAULT 0,
  status            VARCHAR(32) NOT NULL DEFAULT 'running',
  dry_run           TINYINT(1) NOT NULL DEFAULT 0,
  default_namespace VARCHAR(255) NOT NULL DEFAULT '',
  source_label      VARCHAR(128) NOT NULL DEFAULT '',
  source_resource   VARCHAR(64) NOT NULL DEFAULT '',
  workload_kind     VARCHAR(32) NOT NULL DEFAULT '',
  yaml_content      LONGTEXT NOT NULL,
  result_json       LONGTEXT NULL,
  result_count      INT NOT NULL DEFAULT 0,
  summary           VARCHAR(512) NOT NULL DEFAULT '',
  error_message     TEXT NULL,
  created_by        BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_by_name   VARCHAR(80) NOT NULL DEFAULT '',
  created_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX idx_manifest_apply_cluster_created (cluster_id, created_at),
  INDEX idx_manifest_apply_status_created (status, created_at),
  INDEX idx_manifest_apply_dry_run_created (dry_run, created_at),
  INDEX idx_manifest_apply_user_created (created_by, created_at),
  INDEX idx_manifest_apply_namespace (default_namespace)
);