CREATE TABLE IF NOT EXISTS ai_tool_calls (
  id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  conversation_id   BIGINT UNSIGNED NOT NULL,
  message_id        BIGINT UNSIGNED NULL,
  cluster_id        BIGINT UNSIGNED NOT NULL DEFAULT 0,
  tool_name         VARCHAR(120) NOT NULL,
  tool_kind         VARCHAR(32) NOT NULL DEFAULT 'query',
  command_text      TEXT NULL,
  params_json       JSON NULL,
  execution_mode    VARCHAR(32) NOT NULL DEFAULT 'proposal',
  status            VARCHAR(32) NOT NULL DEFAULT 'pending',
  risk_level        VARCHAR(32) NOT NULL DEFAULT 'low',
  confirm_level     VARCHAR(32) NOT NULL DEFAULT 'single',
  result_summary    VARCHAR(512) NOT NULL DEFAULT '',
  result_json       JSON NULL,
  error_message     TEXT NULL,
  created_by        BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_by_name   VARCHAR(80) NOT NULL DEFAULT '',
  created_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_ai_tool_calls_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_tool_calls_message FOREIGN KEY (message_id) REFERENCES ai_messages(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_tool_calls_cluster FOREIGN KEY (cluster_id) REFERENCES clusters(id) ON DELETE RESTRICT,
  INDEX idx_ai_tool_calls_status_created (status, created_at),
  INDEX idx_ai_tool_calls_cluster_created (cluster_id, created_at),
  INDEX idx_ai_tool_calls_message (message_id)
);

CREATE TABLE IF NOT EXISTS ai_action_proposals (
  id                   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  conversation_id      BIGINT UNSIGNED NOT NULL,
  message_id           BIGINT UNSIGNED NULL,
  tool_call_id         BIGINT UNSIGNED NULL,
  cluster_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
  action_type          VARCHAR(64) NOT NULL,
  target_kind          VARCHAR(64) NOT NULL DEFAULT '',
  target_namespace     VARCHAR(255) NOT NULL DEFAULT '',
  target_name          VARCHAR(255) NOT NULL DEFAULT '',
  risk_level           VARCHAR(32) NOT NULL DEFAULT 'low',
  confirm_level        VARCHAR(32) NOT NULL DEFAULT 'single',
  status               VARCHAR(32) NOT NULL DEFAULT 'draft',
  title                VARCHAR(255) NOT NULL DEFAULT '',
  summary              VARCHAR(512) NOT NULL DEFAULT '',
  change_json          JSON NULL,
  created_by           BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_by_name      VARCHAR(80) NOT NULL DEFAULT '',
  approved_by          BIGINT UNSIGNED NULL,
  approved_by_name     VARCHAR(80) NOT NULL DEFAULT '',
  approved_at          DATETIME(3) NULL,
  second_approved_by   BIGINT UNSIGNED NULL,
  second_approved_name VARCHAR(80) NOT NULL DEFAULT '',
  second_approved_at   DATETIME(3) NULL,
  created_at           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_ai_action_proposals_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_action_proposals_message FOREIGN KEY (message_id) REFERENCES ai_messages(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_action_proposals_tool_call FOREIGN KEY (tool_call_id) REFERENCES ai_tool_calls(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_action_proposals_cluster FOREIGN KEY (cluster_id) REFERENCES clusters(id) ON DELETE RESTRICT,
  INDEX idx_ai_action_proposals_status_created (status, created_at),
  INDEX idx_ai_action_proposals_cluster_created (cluster_id, created_at),
  INDEX idx_ai_action_proposals_risk_status (risk_level, status)
);

CREATE TABLE IF NOT EXISTS ai_action_executions (
  id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  proposal_id       BIGINT UNSIGNED NOT NULL,
  conversation_id   BIGINT UNSIGNED NOT NULL,
  cluster_id        BIGINT UNSIGNED NOT NULL DEFAULT 0,
  execution_no      INT NOT NULL DEFAULT 1,
  status            VARCHAR(32) NOT NULL DEFAULT 'pending',
  started_at        DATETIME(3) NULL,
  finished_at       DATETIME(3) NULL,
  operator_id       BIGINT UNSIGNED NOT NULL DEFAULT 0,
  operator_name     VARCHAR(80) NOT NULL DEFAULT '',
  command_snapshot  TEXT NULL,
  result_json       JSON NULL,
  error_message     TEXT NULL,
  created_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_ai_action_executions_proposal FOREIGN KEY (proposal_id) REFERENCES ai_action_proposals(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_action_executions_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_action_executions_cluster FOREIGN KEY (cluster_id) REFERENCES clusters(id) ON DELETE RESTRICT,
  INDEX idx_ai_action_executions_status_created (status, created_at),
  INDEX idx_ai_action_executions_cluster_created (cluster_id, created_at)
);
