CREATE TABLE IF NOT EXISTS ai_uploaded_files (
  id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  conversation_id   BIGINT UNSIGNED NULL,
  message_id        BIGINT UNSIGNED NULL,
  storage_path      VARCHAR(255) NOT NULL,
  original_name     VARCHAR(255) NOT NULL DEFAULT '',
  content_type      VARCHAR(120) NOT NULL DEFAULT '',
  file_size         BIGINT NOT NULL DEFAULT 0,
  purpose           VARCHAR(32) NOT NULL DEFAULT 'chat',
  status            VARCHAR(32) NOT NULL DEFAULT 'active',
  sha256            CHAR(64) NOT NULL DEFAULT '',
  created_by        BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_by_name   VARCHAR(80) NOT NULL DEFAULT '',
  created_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at        DATETIME(3) NULL,
  CONSTRAINT fk_ai_uploaded_files_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_uploaded_files_message FOREIGN KEY (message_id) REFERENCES ai_messages(id) ON DELETE SET NULL,
  INDEX idx_ai_uploaded_files_purpose_created (purpose, created_at),
  INDEX idx_ai_uploaded_files_deleted (deleted_at),
  INDEX idx_ai_uploaded_files_sha256 (sha256)
);

CREATE TABLE IF NOT EXISTS ai_usage_records (
  id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  conversation_id   BIGINT UNSIGNED NULL,
  message_id        BIGINT UNSIGNED NULL,
  provider_id       BIGINT UNSIGNED NULL,
  model_id          BIGINT UNSIGNED NULL,
  usage_type        VARCHAR(32) NOT NULL DEFAULT 'chat',
  request_tokens    INT NOT NULL DEFAULT 0,
  response_tokens   INT NOT NULL DEFAULT 0,
  total_tokens      INT NOT NULL DEFAULT 0,
  image_count       INT NOT NULL DEFAULT 0,
  estimated_cost    DECIMAL(16,6) NOT NULL DEFAULT 0,
  currency          VARCHAR(16) NOT NULL DEFAULT 'USD',
  latency_ms        INT NOT NULL DEFAULT 0,
  meta_json         JSON NULL,
  created_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_ai_usage_records_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_usage_records_message FOREIGN KEY (message_id) REFERENCES ai_messages(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_usage_records_provider FOREIGN KEY (provider_id) REFERENCES ai_providers(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_usage_records_model FOREIGN KEY (model_id) REFERENCES ai_models(id) ON DELETE SET NULL,
  INDEX idx_ai_usage_records_type_created (usage_type, created_at),
  INDEX idx_ai_usage_records_provider_created (provider_id, created_at),
  INDEX idx_ai_usage_records_model_created (model_id, created_at)
);
