CREATE TABLE IF NOT EXISTS automation_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  mode VARCHAR(16) NOT NULL DEFAULT 'manual',
  job_type VARCHAR(32) NOT NULL DEFAULT 'inspection',
  env VARCHAR(16) NOT NULL DEFAULT 'prod',
  status VARCHAR(16) NOT NULL DEFAULT 'enabled',
  risk_level VARCHAR(16) NOT NULL DEFAULT 'medium',
  approval_mode VARCHAR(16) NOT NULL DEFAULT 'manual',
  strategy VARCHAR(16) NOT NULL DEFAULT 'batch',
  concurrency INT NOT NULL DEFAULT 5,
  timeout_sec INT NOT NULL DEFAULT 1800,
  template_id BIGINT UNSIGNED NULL,
  cron VARCHAR(64) NULL,
  targets TEXT NULL,
  limit_spec VARCHAR(255) NULL,
  vars JSON NULL,
  change_window VARCHAR(255) NULL,
  rollback_plan TEXT NULL,
  last_run_task_id BIGINT UNSIGNED NULL,
  last_run_status VARCHAR(32) NULL,
  last_run_at DATETIME(3) NULL,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  INDEX idx_automation_jobs_name (name),
  INDEX idx_automation_jobs_mode (mode),
  INDEX idx_automation_jobs_type (job_type),
  INDEX idx_automation_jobs_env (env),
  INDEX idx_automation_jobs_status (status),
  INDEX idx_automation_jobs_risk (risk_level),
  INDEX idx_automation_jobs_approval (approval_mode),
  INDEX idx_automation_jobs_template_id (template_id),
  INDEX idx_automation_jobs_deleted (deleted_at),
  INDEX idx_automation_jobs_last_run_at (last_run_at)
);
