CREATE TABLE IF NOT EXISTS automation_catalog_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  category VARCHAR(64) NOT NULL,
  description VARCHAR(255) NULL,
  recommended_version VARCHAR(32) NOT NULL DEFAULT 'latest',
  tags JSON NULL,
  published TINYINT(1) NOT NULL DEFAULT 1,
  visibility VARCHAR(16) NOT NULL DEFAULT 'public',
  icon_url TEXT NULL,
  template_id BIGINT UNSIGNED NOT NULL,
  template_version VARCHAR(32) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  INDEX idx_automation_catalog_items_name (name),
  INDEX idx_automation_catalog_items_category (category),
  INDEX idx_automation_catalog_items_published (published),
  INDEX idx_automation_catalog_items_visibility (visibility),
  INDEX idx_automation_catalog_items_template_id (template_id),
  INDEX idx_automation_catalog_items_deleted (deleted_at)
);