CREATE TABLE IF NOT EXISTS app_releases (
  id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name             VARCHAR(160)    NOT NULL,
  cluster_id       BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cluster_name     VARCHAR(120)    NOT NULL DEFAULT '',
  namespace        VARCHAR(64)     NOT NULL DEFAULT 'default',
  template_id      BIGINT UNSIGNED NOT NULL DEFAULT 0,
  template_name    VARCHAR(120)    NOT NULL DEFAULT '',
  template_version VARCHAR(32)     NOT NULL DEFAULT '',
  status           VARCHAR(16)     NOT NULL DEFAULT 'progressing',
  current_revision INT             NOT NULL DEFAULT 1,
  desired_revision INT             NOT NULL DEFAULT 1,
  strategy         VARCHAR(16)     NOT NULL DEFAULT 'rolling',
  replicas         VARCHAR(16)     NOT NULL DEFAULT '0/1',
  health_score     INT             NOT NULL DEFAULT 70,
  `values`         JSON,
  last_event       VARCHAR(512)    NOT NULL DEFAULT '',
  operator         VARCHAR(64)     NOT NULL DEFAULT '',
  paused           TINYINT(1)      NOT NULL DEFAULT 0,
  created_by       BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_by       BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at       DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at       DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at       DATETIME(3)     NULL,
  INDEX idx_app_releases_name     (name),
  INDEX idx_app_releases_cluster  (cluster_id),
  INDEX idx_app_releases_ns       (namespace),
  INDEX idx_app_releases_template (template_id),
  INDEX idx_app_releases_status   (status),
  INDEX idx_app_releases_deleted  (deleted_at)
);
