CREATE TABLE IF NOT EXISTS app_release_revisions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  release_id BIGINT UNSIGNED NOT NULL,
  revision INT NOT NULL,
  template_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  template_name VARCHAR(120) NOT NULL DEFAULT '',
  template_version VARCHAR(32) NOT NULL DEFAULT '',
  compose_manifest LONGTEXT NOT NULL,
  env_content LONGTEXT NULL,
  env_override LONGTEXT NULL,
  `values` JSON NULL,
  project_name VARCHAR(128) NOT NULL DEFAULT '',
  install_dir VARCHAR(256) NOT NULL DEFAULT '',
  pull_images TINYINT(1) NOT NULL DEFAULT 1,
  auto_install_docker TINYINT(1) NOT NULL DEFAULT 1,
  auto_install_compose TINYINT(1) NOT NULL DEFAULT 1,
  operator VARCHAR(64) NOT NULL DEFAULT '',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_app_release_revisions_release_revision (release_id, revision),
  KEY idx_app_release_revisions_release_id (release_id)
);