// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/03_学习/soft/k8s-platform/frontend/src/models/cluster';
import model_2 from 'D:/03_学习/soft/k8s-platform/frontend/src/models/theme';
import model_3 from 'D:/03_学习/soft/k8s-platform/frontend/src/models/user';
import model_4 from 'D:/03_学习/soft/k8s-platform/frontend/src/.umi-production/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'cluster', model: model_1 },
model_2: { namespace: 'theme', model: model_2 },
model_3: { namespace: 'user', model: model_3 },
model_4: { namespace: '@@initialState', model: model_4 },
} as const
