// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'D:/03_学习/soft/k8s-platform/frontend/src/.umi-production/plugin-access';
export { useAntdConfig, useAntdConfigSetter } from 'D:/03_学习/soft/k8s-platform/frontend/src/.umi-production/plugin-antd';
export { Provider, useModel } from 'D:/03_学习/soft/k8s-platform/frontend/src/.umi-production/plugin-model';
export { InfiniteQueryObserver, IsRestoringProvider, MutationCache, MutationObserver, QueriesObserver, QueryCache, QueryClient, QueryClientProvider, QueryErrorResetBoundary, QueryObserver, infiniteQueryOptions, queryOptions, useInfiniteQuery, useIsFetching, useIsMutating, useIsRestoring, useMutation, useMutationState, useQueries, useQuery, useQueryClient, useQueryErrorResetBoundary, useSuspenseInfiniteQuery, useSuspenseQueries, useSuspenseQuery } from 'D:/03_学习/soft/k8s-platform/frontend/src/.umi-production/plugin-reactQuery';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'D:/03_学习/soft/k8s-platform/frontend/src/.umi-production/plugin-request';
// plugins types.d.ts
export * from 'D:/03_学习/soft/k8s-platform/frontend/src/.umi-production/plugin-access/types.d';
export * from 'D:/03_学习/soft/k8s-platform/frontend/src/.umi-production/plugin-antd/types.d';
export * from 'D:/03_学习/soft/k8s-platform/frontend/src/.umi-production/plugin-layout/types.d';
export * from 'D:/03_学习/soft/k8s-platform/frontend/src/.umi-production/plugin-reactQuery/types.d';
export * from 'D:/03_学习/soft/k8s-platform/frontend/src/.umi-production/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/03_学习/soft/k8s-platform/frontend/node_modules/.pnpm/@umijs+renderer-react@4.6.6_f6ef47ccb6c1da1a053b72892ec06e00/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from 'D:/03_学习/soft/k8s-platform/frontend/node_modules/.pnpm/@umijs+renderer-react@4.6.6_f6ef47ccb6c1da1a053b72892ec06e00/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/03_学习/soft/k8s-platform/frontend/node_modules/.pnpm/umi@4.6.65_@babel+core@7.29_1bbca118541480622b7e273d97f29a8e/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
