// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export {
  QueryClient,
  QueryCache,
  MutationCache,
  QueryObserver,
  InfiniteQueryObserver,
  QueriesObserver,
  MutationObserver,
  useQuery,
  useQueries,
  useInfiniteQuery,
  useMutation,
  useIsFetching,
  useIsMutating,
  useMutationState,
  useSuspenseQuery,
  useSuspenseInfiniteQuery,
  useSuspenseQueries,
  queryOptions,
  infiniteQueryOptions,
  QueryClientProvider,
  useQueryClient,
  QueryErrorResetBoundary,
  useQueryErrorResetBoundary,
  useIsRestoring,
  IsRestoringProvider
} from 'D:/03_学习/soft/k8s-platform/frontend/node_modules/@tanstack/react-query';
