// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import {
  
  QueryClient,
  QueryClientProvider
} from 'D:/03_学习/soft/k8s-platform/frontend/node_modules/@tanstack/react-query';

import { reactQuery as reactQueryConfig } from '@/app';
const client = new QueryClient(reactQueryConfig.queryClient || {});
export function rootContainer(container) {
  return (
    <QueryClientProvider
      client={client}
      
    >
      {container}
      
    </QueryClientProvider>
  );
}
