// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { QueryClientConfig } from 'D:/03_学习/soft/k8s-platform/frontend/node_modules/@tanstack/react-query';


export type RuntimeReactQueryType = {
  
  queryClient?: QueryClientConfig
}
