export type ManifestTemplate = {
  key: string
  category: string
  title: string
  description: string
  yaml: string
}

const ns = '${namespace}'

export const manifestTemplates: ManifestTemplate[] = [
  { key: 'deployment', category: '工作负载', title: 'Deployment + Service', description: '无状态应用、健康检查、资源配额与服务发现', yaml: `apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: web\n  namespace: ${ns}\n  labels:\n    app.kubernetes.io/name: web\nspec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app.kubernetes.io/name: web\n  template:\n    metadata:\n      labels:\n        app.kubernetes.io/name: web\n    spec:\n      containers:\n        - name: web\n          image: nginx:1.27-alpine\n          ports:\n            - name: http\n              containerPort: 80\n          readinessProbe:\n            httpGet: { path: /, port: http }\n          livenessProbe:\n            httpGet: { path: /, port: http }\n          resources:\n            requests: { cpu: 100m, memory: 128Mi }\n            limits: { cpu: 500m, memory: 512Mi }\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: web\n  namespace: ${ns}\nspec:\n  selector:\n    app.kubernetes.io/name: web\n  ports:\n    - name: http\n      port: 80\n      targetPort: http\n` },
  { key: 'statefulset', category: '工作负载', title: 'StatefulSet', description: '稳定网络标识与持久卷声明模板', yaml: `apiVersion: apps/v1\nkind: StatefulSet\nmetadata:\n  name: database\n  namespace: ${ns}\nspec:\n  serviceName: database\n  replicas: 1\n  selector:\n    matchLabels: { app: database }\n  template:\n    metadata:\n      labels: { app: database }\n    spec:\n      containers:\n        - name: database\n          image: postgres:16-alpine\n          ports: [{ name: tcp, containerPort: 5432 }]\n          env:\n            - name: POSTGRES_PASSWORD\n              valueFrom: { secretKeyRef: { name: database, key: password } }\n          volumeMounts: [{ name: data, mountPath: /var/lib/postgresql/data }]\n          resources:\n            requests: { cpu: 250m, memory: 256Mi }\n            limits: { cpu: "1", memory: 1Gi }\n  volumeClaimTemplates:\n    - metadata: { name: data }\n      spec:\n        accessModes: [ReadWriteOnce]\n        resources: { requests: { storage: 10Gi } }\n` },
  { key: 'cronjob', category: '工作负载', title: 'CronJob', description: '带并发策略、历史限制与失败重试', yaml: `apiVersion: batch/v1\nkind: CronJob\nmetadata:\n  name: scheduled-task\n  namespace: ${ns}\nspec:\n  schedule: "0 * * * *"\n  concurrencyPolicy: Forbid\n  successfulJobsHistoryLimit: 3\n  failedJobsHistoryLimit: 3\n  jobTemplate:\n    spec:\n      backoffLimit: 2\n      template:\n        spec:\n          restartPolicy: Never\n          containers:\n            - name: task\n              image: busybox:1.36\n              command: [sh, -c, date]\n` },
  { key: 'config', category: '配置', title: 'ConfigMap + Secret', description: '应用配置和敏感数据引用示例', yaml: `apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: app-config\n  namespace: ${ns}\ndata:\n  APP_ENV: production\n---\napiVersion: v1\nkind: Secret\nmetadata:\n  name: app-secret\n  namespace: ${ns}\ntype: Opaque\nstringData:\n  password: change-me\n` },
  { key: 'ingress', category: '网络', title: 'Ingress', description: 'IngressClass、TLS 与路径路由', yaml: `apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: web\n  namespace: ${ns}\nspec:\n  ingressClassName: nginx\n  tls:\n    - hosts: [app.example.com]\n      secretName: app-tls\n  rules:\n    - host: app.example.com\n      http:\n        paths:\n          - path: /\n            pathType: Prefix\n            backend:\n              service: { name: web, port: { number: 80 } }\n` },
  { key: 'network-policy', category: '网络', title: 'NetworkPolicy', description: '默认拒绝并仅放行指定应用流量', yaml: `apiVersion: networking.k8s.io/v1\nkind: NetworkPolicy\nmetadata:\n  name: web-ingress\n  namespace: ${ns}\nspec:\n  podSelector:\n    matchLabels: { app.kubernetes.io/name: web }\n  policyTypes: [Ingress, Egress]\n  ingress:\n    - from:\n        - namespaceSelector: {}\n      ports: [{ protocol: TCP, port: 80 }]\n  egress:\n    - to: [{ namespaceSelector: {} }]\n` },
  { key: 'pvc', category: '存储', title: 'PersistentVolumeClaim', description: '动态存储卷声明', yaml: `apiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  name: app-data\n  namespace: ${ns}\nspec:\n  accessModes: [ReadWriteOnce]\n  resources:\n    requests: { storage: 10Gi }\n` },
  { key: 'autoscaling', category: '弹性与可用性', title: 'HPA + PDB', description: '自动扩缩容与滚动维护可用性保护', yaml: `apiVersion: autoscaling/v2\nkind: HorizontalPodAutoscaler\nmetadata:\n  name: web\n  namespace: ${ns}\nspec:\n  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: web }\n  minReplicas: 2\n  maxReplicas: 10\n  metrics:\n    - type: Resource\n      resource:\n        name: cpu\n        target: { type: Utilization, averageUtilization: 70 }\n---\napiVersion: policy/v1\nkind: PodDisruptionBudget\nmetadata:\n  name: web\n  namespace: ${ns}\nspec:\n  minAvailable: 1\n  selector:\n    matchLabels: { app.kubernetes.io/name: web }\n` },
  { key: 'rbac', category: '访问控制', title: 'ServiceAccount + RBAC', description: '命名空间内只读最小权限', yaml: `apiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: app-reader\n  namespace: ${ns}\n---\napiVersion: rbac.authorization.k8s.io/v1\nkind: Role\nmetadata:\n  name: app-reader\n  namespace: ${ns}\nrules:\n  - apiGroups: [""]\n    resources: [pods, services, configmaps]\n    verbs: [get, list, watch]\n---\napiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding\nmetadata:\n  name: app-reader\n  namespace: ${ns}\nsubjects:\n  - kind: ServiceAccount\n    name: app-reader\n    namespace: ${ns}\nroleRef: { apiGroup: rbac.authorization.k8s.io, kind: Role, name: app-reader }\n` },
  { key: 'namespace', category: '集群基础', title: 'Namespace + ResourceQuota', description: '团队隔离与资源预算', yaml: `apiVersion: v1\nkind: Namespace\nmetadata:\n  name: ${ns}\n  labels:\n    pod-security.kubernetes.io/enforce: baseline\n---\napiVersion: v1\nkind: ResourceQuota\nmetadata:\n  name: namespace-quota\n  namespace: ${ns}\nspec:\n  hard:\n    requests.cpu: "4"\n    requests.memory: 8Gi\n    limits.cpu: "8"\n    limits.memory: 16Gi\n    pods: "50"\n` },
]

export function renderManifestTemplate(template: ManifestTemplate, namespace: string) {
  return template.yaml.replaceAll('${namespace}', namespace || 'default')
}
